name: Node.js CI with PORT

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    setup-and-run:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "21"

            - name: Install dependencies
              run: npm install

            - name: Setup PORT variable
              env:
                  PORT: ${{ secrets.PORT }}
              run: |
                  echo "PORT is set to $PORT"

            - name: Start the application
              env:
                  PORT: ${{ secrets.PORT }}
              run: |
                  echo "Starting application on PORT $PORT"
                  nohup npm start & # Run app in the background with nohup

            - name: Wait for the server to start
              run: sleep 10 # Wait to ensure the server is running

            - name: Test application
              run: |
                  echo "Testing application on http://localhost:${{ secrets.PORT }}"
                  curl -v http://localhost:${{ secrets.PORT }}
