name: Node.js CI with PORT

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    setup-and-run:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "21" # Node.js version

            - name: Install dependencies
              run: npm install

            - name: Setup PORT variable
              env:
                  PORT: ${{ secrets.PORT }} # Reference GitHub secret
              run: |
                  echo "PORT is set to $PORT"

            - name: Start the application
              env:
                  PORT: ${{ secrets.PORT }}
              run: |
                  echo "Starting application on PORT $PORT"
                  npm start &

            - name: Test application
              run: |
                  echo "Waiting for application to start..."
                  sleep 5
                  curl http://127.0.0.1:${{ secrets.PORT }}/
